addSbtPlugin("org.scoverage"  % "sbt-scoverage"       % "2.3.1")
addSbtPlugin("com.github.sbt" % "sbt-jacoco"          % "3.4.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.1")
addSbtPlugin("com.github.sbt" % "sbt-release"         % "1.4.0")
addSbtPlugin("com.github.sbt.junit" % "sbt-jupiter-interface" % "0.15.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.4")
