name: CI

on: workflow_dispatch

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - id: co
        name: Checkout source code
        uses: actions/checkout@v4
      - id: cache
        name: Cache source
        uses: actions/cache@v4
        with:
          path: ziota2
          key: src

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: prep-build
        name: Setup SBT
        uses: sbt/setup-sbt@v1
      - id: restore
        name: Restore source
        uses: actions/cache/restore@v4
        with:
          path: ziota2
          key: src
      - id: build
        name: Build source
        run: sbt compile

