name: CI

on: workflow_dispatch

jobs:
  checkout:
    name: Checkout
    runs-on: ubutu-latest
    steps:
      - id: co
        name: Checkout source code
        uses: actions/checkout@v4

  build:
    name: Build
    runs-on: ubutu-latest
    steps:
      - id: build
        name: Build source
        uses: sbt/setup-sbt@v1

