name: CI
# updated
on:
  workflow_dispatch:
  push:
      branches:
        - main
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - id: co
        name: Checkout source code
        uses: actions/checkout@v4
      - id: cache
        name: Cache source
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: src-${{ github.run_id }}
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - id: prep-build
        name: Setup SBT
        uses: sbt/setup-sbt@v1
      - id: restore_source
        name: Restore source
        uses: actions/cache/restore@v4.2.3
        with:
          path: ${{ github.workspace }}
          key: src-${{ github.run_id }}
      - id: restore_docker_images
        name: Restore Docker image
        uses: actions/cache/restore@v4.2.3
        with:
          path: .docker_images/
          key: docker-images
          fail-on-cache-miss: false
      - id: load_docker_image
        name: Load Docker image
        if: ${{ steps.restore_docker_images.outputs.cache-hit == 'true' }}
        run: |
          docker load -i ./docker_images/wiremock-wiremock-3.12.1.tar
          docker load -i ./docker_images/confluentinc-cp-kafka-7.9.0.tar
      - id: build
        name: Build and Test
        run: sbt test
      - id: save_docker_image
        if: ${{ steps.restore_docker_images.outputs.cache-hit != 'true' }}
        run: |
          mkdir ./docker_images
          docker save wiremock/wiremock:3.12.1    -o ./docker_images/wiremock-wiremock-3.12.1.tar
          docker save confluentinc/cp-kafka:7.9.0 -o ./docker_images/confluentinc-cp-kafka-7.9.0.tar
      - id: cache_docker_image
        uses: actions/cache/save@v4.2.3
        if: ${{ steps.restore_docker_images.outputs.cache-hit != 'true' }}
        with:
          path: ./docker_images/
          key: docker-images

