name: CI

on: workflow_dispatch

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - id: co
        name: Checkout source code
        uses: actions/checkout@v4

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: prep-build
        name: Setup SBT
        uses: sbt/setup-sbt@v1
      - id: build
        name: Build source
        run: sbt compile

