name: Manual
on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        required: true
        description: OS to tests
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      os: fromJSON(format("[{0}]", "${{ inputs.os }}"))
    steps:
      - name: prepare
        run: |
          echo "os=${{ env.os }}" >> $GITHUB_OUTPUT

  print:
    runs-on: ubuntu-latest
    env:
      os: "A, B"
    strategy:
      matrix:
        os: ${{ env.os }}
    steps:
      - name: print_title
        run:
          echo ${{ matrix.os }}

