name: Manual
on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        required: true
        description: OS to tests
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      = name: prepare
        run:|
          os=${{ fromJSON(format("[{0}]", "${{ inputs.os }}")) }}
          echo "os=$os" >> $GITHUB_OUTPUT

  print:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ${{ need.steps.outputs.os }}
    steps:
      - name: print_title
        run:
          echo ${{ matrix.os }}

