name: PR
on:
  pull_request:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: j1
        run: |
          echo "j1: ${{ github.event_name }} ${{ github.base_ref }} ${{ github.sha }} ${{ github.head_ref }} ${{ github.ref_name }}"